# Build settings
theme: minima
google_analytics: G-Y0051BGKMZ
title: Replicable BWAS with Moderate Sample Sizes
author: Tamas Spisak, Ulrike Bingel & Tor Wager
email: tamas.spisak@uk-essen.de
description: > # this means to ignore newlines until "show_excerpts:"
  This webpage accompanies the paper "Multivariate BWAS can be replicable with moderate sample sizes in some cases"
  by Tamas Spisak, Ulrike Bingel & Tor Wager, accepted in Nature.

# Minima date format
# refer to https://shopify.github.io/liquid/filters/date/ if you want to customize this
#minima:
#  date_format: "%b %-d, %Y"

# generate social links in footer
#social_links:
#   - { platform: github,         user_url: "https://github.com/spisakt/BWAS_comment" }
#   - { platform: twitter,        user_url: "https://twitter.com/spisaktamas" }
#   - { platform: youtube,        user_url: "https://www.youtube.com/pnilab" }
twitter_username: spisaktamas
github_username:  pni-lab
youtube_username: pni-lab

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
#header_pages:
# - summary
# - results
# - links

plugins:
 - jekyll-seo-tag
