name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Get tag
      id: tag
      uses: oprypin/find-latest-tag@v1
      with:
        repository: spisakt/BWAS_comment  # The repository to scan.\
        
    - name: Build the Docker image
      run: |
        docker build . --file Dockerfile --tag tspisak/bwasrep:latest
        docker tag pnilab/bwasrep:latest pnilab/bwasrep:${{steps.tag.outputs.tag}}
      
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USER }}
        password: ${{ secrets.DOCKER_PASSWORD }}
          
    - name: Docker Push
      run: |
        VER=`echo ${{steps.tag.outputs.tag}} | awk -F'[.-]' '{print $1 "." $2 "." $3}'` #major.minor.patch
        docker push pnilab/bwasrep:latest
        docker push pnilab/bwasrep:${{steps.tag.outputs.tag}}
